# October 2016 Indy UseR group meeting


###  New R tools for workflow management, testing, and reproducibility - Talk by Will Landau ([link to presentation](workflow-toolkit.pdf))

*Abstract*

Packages downsize, remake, remakeGenerator, and parallelRemake constitute a workflow management, testing, and reproducibility toolkit for R users with time-consuming tasks. With downsize, the user can toggle the test and production versions of a workflow with the flip of a global option. This approach circumvents tedium and human error because the test can run quickly and still closely approximate the original task at hand. The remake package by Rich FitzJohn is a friendly, R-focused build system based on the underlying concepts of GNU Make. By automatically rebuilding only the changed parts of an ongoing project, remake brings the results up to date with the code without rerunning the whole workflow from scratch. The remakeGenerator and parallelRemake packages add functionality to remake. RemakeGenerator efficiently produces flexible data analysis plans for remake that would otherwise be too cumbersome to write by hand, and it uses parallelRemake to write overarching Makefiles that support distributed parallel computing.

    
